### ISSUE TITLE
Functional and Taxonomic Table: Export functionality is at odds with selection.

### ISSUE THREAD

**Issue by nielshanson** [hallamlab/MetaPathwaysGUI#5]
Highlighting rows with the mouse. One might expect that you would just export the highlighted one. If this is not the case we should just disable the selection of more than one cell at a time.

When you export the example below, you get the whole table not what you highlight. Someone might expect this.

![screen shot 2014-06-12 at 1 45 03 pm](https://cloud.githubusercontent.com/assets/1212175/3263488/73db0692-f272-11e3-97c5-7260edeb1603.png)

**Comment by hallamlab** [comment]
all comments are being incorporated into a future release
